-- ShopAI E-Commerce — Extended Product Seed (50 Products)
-- V16: Specialized categories (Electronics, Clothing, Shoes, Home, Sport)
-- Security: MySQL 8 Compatible | UTF8MB4

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- 1. Insert Products
INSERT INTO products 
  (id, name, slug, description, long_description, price, discounted_price, stock_quantity, sku, brand, category_id, rating_avg, rating_count, is_active, is_featured, tags, meta_title, meta_description, created_at)
VALUES
-- ELEKTRONİK - AKILLI TELEFONLAR (7)
(35, 'Samsung Galaxy S24 Ultra 256GB Titanium', 'samsung-galaxy-s24-ultra-256gb', 'Galaxy S24 Ultra, S Pen entegrasyonu ve yapay zeka destekli kamera sistemiyle profesyonel kullanıcılar için tasarlandı.', '<p>Samsung Galaxy S24 Ultra, 6.8 inç Dynamic AMOLED 2X ekranı ve entegre S Pen ile üretkenliği yeni bir seviyeye taşır. Snapdragon 8 Gen 3 işlemcisi sayesinde olağanüstü performans sunar.</p><ul><li>200 MP ana kamera + yapay zeka zoom</li><li>5000 mAh pil, 45W hızlı şarj</li><li>Titanyum çerçeve, IP68 su geçirmezlik</li><li>12 GB RAM, 256 GB depolama</li><li>Android 14, One UI 6.1</li></ul>', 54999.00, NULL, 87, 'SAM-PHN-S24U', 'Samsung', 7, 0.00, 0, TRUE, FALSE, '["samsung","galaxy","akıllı telefon","s24 ultra","android"]', 'Samsung Galaxy S24 Ultra', 'AI Destekli Akıllı Telefon', NOW()),
(36, 'Apple iPhone 15 Pro 128GB Doğal Titanyum', 'apple-iphone-15-pro-128gb', 'iPhone 15 Pro, A17 Pro çipi ve titanyum tasarımıyla Apple''ın en güçlü akıllı telefonu olmaya devam ediyor.', '<p>iPhone 15 Pro, endüstri standartlarını belirleyen A17 Pro çipiyle oyun ve profesyonel video çekiminde rakipsiz bir performans sunar. USB-C bağlantısı ile hız ve esneklik bir arada.</p><ul><li>48 MP ana kamera, ProRAW & ProRes video</li><li>Titanyum çerçeve, Ceramic Shield ön cam</li><li>Action Button özelleştirilebilir tuş</li><li>USB 3 hızında USB-C</li><li>iOS 17 ve sonraki güncellemeler</li></ul>', 52999.00, NULL, 124, 'APL-PHN-IP15P', 'Apple', 7, 0.00, 0, TRUE, FALSE, '["apple","iphone","ios","akıllı telefon","titanyum"]', 'Apple iPhone 15 Pro', 'Gelişmiş Kamera ve Performans', NOW()),
(37, 'Xiaomi 14 Pro 512GB Siyah', 'xiaomi-14-pro-512gb-siyah', 'Leica optikleri ve Snapdragon 8 Gen 3 işlemcisiyle Xiaomi 14 Pro fotoğraf tutkunlarının tercihi.', '<p>Xiaomi 14 Pro, Leica ile ortak geliştirilen Summilux lens serisi sayesinde profesyonel fotoğraf kalitesini cebinize taşır. HyperOS ile akıllı ekosistem entegrasyonu kusursuz çalışır.</p><ul><li>50 MP Leica Summilux ana kamera</li><li>4880 mAh pil, 120W kablolu şarj</li><li>6.73 inç LTPO AMOLED, 120Hz</li><li>512 GB depolama, 16 GB RAM</li><li>Wi-Fi 7, Bluetooth 5.4</li></ul>', 42999.00, NULL, 65, 'XMI-PHN-14PRO', 'Xiaomi', 7, 0.00, 0, TRUE, FALSE, '["xiaomi","leica","android","akıllı telefon","5g"]', 'Xiaomi 14 Pro', 'Leica Kameralı Android Amiral Gemisi', NOW()),
(38, 'Google Pixel 8 Pro 256GB Obsidyen', 'google-pixel-8-pro-256gb-obsidyen', 'Google Pixel 8 Pro, yapay zeka destekli özellikler ve saf Android deneyimiyle öne çıkıyor.', '<p>Google Tensor G3 çipi ile güçlendirilen Pixel 8 Pro, fotoğraf düzenleme ve sesli yardımcı özellikleriyle günlük hayatı kolaylaştırır. 7 yıl yazılım güncellemesi garantisi sunar.</p><ul><li>50 MP ana + 48 MP telefoto + 48 MP ultra geniş</li><li>Temperatür sensörü</li><li>4950 mAh pil, 30W şarj</li><li>6.7 inç LTPO OLED, 120Hz</li><li>7 yıl Android & güvenlik güncellemesi</li></ul>', 38999.00, NULL, 43, 'GOG-PHN-PX8P', 'Google', 7, 0.00, 0, TRUE, FALSE, '["google","pixel","android","yapay zeka","kamera"]', 'Google Pixel 8 Pro', 'Yapay Zeka Destekli Fotoğrafçılık', NOW()),
(39, 'OnePlus 12 256GB Silky Black', 'oneplus-12-256gb-silky-black', 'OnePlus 12, Hasselblad kamera sistemi ve 100W SUPERVOOC şarj teknolojisiyle hız odaklı kullanıcılara hitap eder.', '<p>OnePlus 12, Snapdragon 8 Gen 3 işlemcisi ve 100W SUPERVOOC şarj sistemiyle tam şarjı yalnızca 26 dakikada tamamlar. Hasselblad ortaklığı ile renkler doğal ve gerçekçi yansıtılır.</p><ul><li>50 MP Hasselblad ana kamera</li><li>5400 mAh pil, 100W kablolu şarj</li><li>6.82 inç LTPO 4.0 AMOLED</li><li>16 GB RAM, 256 GB UFS 4.0</li><li>OxygenOS 14</li></ul>', 32999.00, NULL, 78, 'OPL-PHN-OP12', 'OnePlus', 7, 0.00, 0, TRUE, FALSE, '["oneplus","android","hızlı şarj","hasselblad","5g"]', 'OnePlus 12', 'Süper Hızlı Şarjlı Performans Canavarı', NOW()),

-- ELEKTRONİK - LAPTOP (8)
(40, 'Apple MacBook Pro 14" M3 Pro 512GB Uzay Siyahı', 'apple-macbook-pro-14-m3-pro-512gb', 'M3 Pro çipiyle MacBook Pro 14, video prodüksiyonu ve yazılım geliştirme için rakipsiz performans sunar.', '<p>Apple M3 Pro çipi, 12 CPU ve 18 GPU çekirdeği ile profesyonel iş yüklerini soğutma sorunu yaşamadan kaldırır. Liquid Retina XDR ekranıyla renk doğruluğu endüstri standardını belirler.</p><ul><li>M3 Pro çip, 18 GB birleşik bellek</li><li>Liquid Retina XDR, 120Hz ProMotion</li><li>22 saate kadar pil ömrü</li><li>3 Thunderbolt 4, HDMI, SD kart</li><li>macOS Sonoma</li></ul>', 89999.00, NULL, 34, 'APL-LAP-MBP14M3', 'Apple', 8, 0.00, 0, TRUE, FALSE, '["apple","macbook","m3","laptop","macos"]', 'Apple MacBook Pro M3', 'Profesyoneller İçin Dizüstü', NOW()),
(41, 'Lenovo ThinkPad X1 Carbon Gen 12 Intel i7', 'lenovo-thinkpad-x1-carbon-gen12', 'ThinkPad X1 Carbon Gen 12, kurumsal kullanıcılar için üstün güvenlik ve hafifliği bir arada sunar.', '<p>Sadece 1.12 kg ağırlığıyla ThinkPad X1 Carbon Gen 12, Intel Core Ultra 7 işlemcisi ve 32 GB LPDDR5 RAM ile profesyonel görevlerde kesintisiz performans sağlar. MIL-SPEC 810H sertifikalıdır.</p><ul><li>Intel Core Ultra 7 165H işlemci</li><li>14 inç IPS Anti-glare, 2.8K ekran</li><li>32 GB RAM, 1 TB NVMe SSD</li><li>57 Wh pil, 65W şarj</li><li>Parmak izi okuyucu ve yüz tanıma</li></ul>', 74999.00, NULL, 22, 'LNV-LAP-X1CG12', 'Lenovo', 8, 0.00, 0, TRUE, FALSE, '["lenovo","thinkpad","laptop","kurumsal","intel"]', 'ThinkPad X1 Carbon', 'Hafif ve Dayanıklı İş Bilgisayarı', NOW()),
(42, 'ASUS ROG Zephyrus G14 AMD Ryzen 9 RTX 4060', 'asus-rog-zephyrus-g14-ryzen9-rtx4060', 'ROG Zephyrus G14, 14 inç kompakt gövdesinde RTX 4060 ile oyun dünyasında fark yaratan bir gaming laptop.', '<p>ASUS ROG Zephyrus G14, AMD Ryzen 9 8945HS and NVIDIA RTX 4060 kombinasyonuyla yüksek FPS oyun deneyimi sunarken 14 inç formata sığar. AniMe Matrix LED kapak opsiyonu görsel kimliği tamamlar.</p><ul><li>AMD Ryzen 9 8945HS, 8 çekirdek</li><li>RTX 4060 8 GB GDDR6</li><li>14 inç QHD+ 165Hz ekran</li><li>16 GB DDR5, 1 TB SSD</li><li>ROG Nebula Display, Dolby Vision</li></ul>', 54999.00, NULL, 41, 'ASS-LAP-G14R9', 'ASUS', 8, 0.00, 0, TRUE, FALSE, '["asus","rog","gaming","laptop","rtx"]', 'ASUS ROG Zephyrus G14', 'Kompakt Oyuncu Laptopu', NOW()),
(43, 'Dell XPS 15 9530 Intel i9 OLED Dokunmatik', 'dell-xps-15-9530-i9-oled', 'Dell XPS 15 OLED, içerik üreticileri için mükemmel renk doğruluğu ve güçlü işlemci performansı sunar.', '<p>Dell XPS 15, 3.5K OLED dokunmatik ekranı ve Intel Core i9-13900H işlemcisiyle video düzenleme ve grafik tasarımda profesyonel bir iş istasyonuna dönüşür. İnce alüminyum kasası taşınabilirliği artırır.</p><ul><li>Intel Core i9-13900H, 24 çekirdek</li><li>3.5K OLED dokunmatik, 60Hz</li><li>32 GB DDR5, 1 TB SSD</li><li>NVIDIA RTX 4060 8 GB</li><li>Thunderbolt 4, SD kart okuyucu</li></ul>', 69999.00, NULL, 18, 'DEL-LAP-XPS15I9', 'Dell', 8, 0.00, 0, TRUE, FALSE, '["dell","xps","oled","laptop","içerik üreticisi"]', 'Dell XPS 15 OLED', 'Zarafet ve Güç Bir Arada', NOW()),

-- ELEKTRONİK - TABLET (9)
(44, 'Apple iPad Pro 12.9" M2 256GB Wi-Fi', 'apple-ipad-pro-12-9-m2-256gb', 'iPad Pro M2, Liquid Retina XDR ekranı ve M2 çipiyle profesyonel çizim ve video düzenlemeye hazır.', '<p>Apple iPad Pro 12.9 inç, mini-LED Liquid Retina XDR ekranı sayesinde 1600 nit tepe parlaklık ve geniş renk gamı sunar. Apple Pencil 2. Nesil ve Magic Keyboard ile tam iş istasyonuna dönüşür.</p><ul><li>Apple M2 çip, 8 çekirdekli GPU</li><li>12.9 inç mini-LED, ProMotion 120Hz</li><li>8 GB RAM, 256 GB depolama</li><li>Thunderbolt 4 USB-C</li><li>iPadOS 17 ve güncellemeler</li></ul>', 44999.00, NULL, 56, 'APL-TAB-IPDP129', 'Apple', 9, 0.00, 0, TRUE, FALSE, '["apple","ipad","tablet","m2","çizim"]', 'Apple iPad Pro M2', 'En Güçlü iPad Deneyimi', NOW()),
(45, 'Samsung Galaxy Tab S9+ 256GB Grafite Wi-Fi', 'samsung-galaxy-tab-s9-plus-256gb', 'Galaxy Tab S9+, Dynamic AMOLED 2X ekranı ve S Pen ile Android tablet deneyimini zirveye taşır.', '<p>Samsung Galaxy Tab S9+, Snapdragon 8 Gen 2 işlemcisi ve 12.4 inç Dynamic AMOLED ekranıyla hem çalışma hem eğlence için ideal. S Pen kutudan çıkar ve DeX modu masaüstü deneyimi sağlar.</p><ul><li>12.4 inç Dynamic AMOLED 2X, 120Hz</li><li>Snapdragon 8 Gen 2, 12 GB RAM</li><li>256 GB depolama, microSD desteği</li><li>S Pen dahil, IP68 su geçirmezlik</li><li>Samsung DeX modu</li></ul>', 32999.00, NULL, 47, 'SAM-TAB-TSP9PLS', 'Samsung', 9, 0.00, 0, TRUE, FALSE, '["samsung","galaxy tab","tablet","s pen","amoled"]', 'Galaxy Tab S9+', 'Android Tablet Dünyasının Zirvesi', NOW()),
(46, 'Lenovo Tab P12 Pro 256GB AMOLED', 'lenovo-tab-p12-pro-256gb-amoled', 'Tab P12 Pro, 12.6 inç AMOLED ekran ve Dolby Vision desteğiyle üstün multimedya deneyimi sunar.', '<p>Lenovo Tab P12 Pro, 12.6 inç 2K AMOLED ekranı ve dört hoparlör sistemiyle film izleme ve müzik keyfi için mükemmel bir tercih. Snapdragon 870 işlemcisi ile sorunsuz çoklu görev yönetimi sağlar.</p><ul><li>12.6 inç 2K AMOLED, 120Hz</li><li>Snapdragon 870, 8 GB RAM</li><li>256 GB depolama</li><li>Dört JBL hoparlör, Dolby Atmos</li><li>10200 mAh pil, 45W şarj</li></ul>', 18999.00, NULL, 63, 'LNV-TAB-P12PRO', 'Lenovo', 9, 0.00, 0, TRUE, FALSE, '["lenovo","tablet","amoled","multimedya","android"]', 'Lenovo Tab P12 Pro', 'Eğlence ve Üretkenlik İçin Tablet', NOW()),

-- ELEKTRONİK - KULAKLIK (10)
(47, 'Sony WH-1000XM5 Kablosuz Gürültü Önleyici Kulaklık', 'sony-wh-1000xm5-kablosuz', 'WH-1000XM5, sektörün en iyi aktif gürültü önleme sistemi ve 30 saatlik pil ömrüyle üstün ses deneyimi sunar.', '<p>Sony WH-1000XM5, yeni nesil 8 mikrofon sistemi ve V1 + QN1 çift işlemcisi sayesinde rakipsiz gürültü önleme performansı sunar. 30mm sürücüler kristal netliğinde ses üretir.</p><ul><li>Endüstri lideri Aktif Gürültü Önleme (ANC)</li><li>30 saat pil ömrü (ANC açık)</li><li>3 dakika şarjla 3 saat kullanım</li><li>Çoklu cihaz bağlantısı (Multipoint)</li><li>Speak-to-Chat, Otomatik oynatma durdurma</li></ul>', 10999.00, NULL, 112, 'SNY-AUD-WH1000X5', 'Sony', 10, 0.00, 0, TRUE, FALSE, '["sony","kulaklık","anc","kablosuz","gürültü önleme"]', 'Sony WH-1000XM5', 'Sessizliğin ve Kalitenin Tanımı', NOW()),
(48, 'Apple AirPods Pro 2. Nesil USB-C', 'apple-airpods-pro-2-usb-c', 'AirPods Pro 2, H2 çipi ile güçlü ANC ve Adaptive Audio özelliğiyle kulak içi kulaklıkta yeni standart belirliyor.', '<p>Apple AirPods Pro 2. Nesil, H2 çipi sayesinde önceki nesle kıyasla 2 kat daha etkili gürültü önleme sunar. Adaptive Audio, ortama göre ses deneyimini otomatik ayarlar ve gerçekten şeffaf bir dinleme sağlar.</p><ul><li>H2 çip, 2x daha güçlü ANC</li><li>Adaptive Audio modu</li><li>6 saat pil + kılıfla 30 saat</li><li>MagSafe & Apple Watch şarjı uyumlu</li><li>IP54 toz ve su direnci</li></ul>', 9499.00, NULL, 143, 'APL-AUD-APPRO2UC', 'Apple', 10, 0.00, 0, TRUE, FALSE, '["apple","airpods","kulaklık","anc","ios"]', 'Apple AirPods Pro 2', 'Kusursuz Ses ve ANC', NOW()),
(49, 'Bose QuietComfort Ultra Headphones Siyah', 'bose-quietcomfort-ultra-headphones-siyah', 'Bose QC Ultra, CustomTune teknolojisi ve Immersive Audio ile kulaklık deneyiminde yeni bir boyut açıyor.', '<p>Bose QuietComfort Ultra, CustomTune ses kalibrasyon teknolojisi ve WorldSpatial Immersive Audio özelliğiyle dinleyiciyi müziğin tam ortasına taşır. 24 saatlik pil ömrü ve katlanabilir tasarımı seyahatte vazgeçilmez kılar.</p><ul><li>Bose en üst düzey ANC teknolojisi</li><li>Immersive Audio (Spatial Sound)</li><li>24 saat pil ömrü</li><li>Çoklu cihaz bağlantısı</li><li>Katlanabilir, seyahat çantalı</li></ul>', 12499.00, NULL, 67, 'BSE-AUD-QCULTRA', 'Bose', 10, 0.00, 0, TRUE, FALSE, '["bose","kulaklık","anc","spatial audio","wireless"]', 'Bose QC Ultra', 'Uzun Süreli Konfor ve Ses', NOW()),

-- GİYİM - TİŞÖRT (11)
(50, 'Nike Dri-FIT ADV TechKnit Ultra Erkek Tişört', 'nike-dri-fit-adv-techknit-ultra-tisort', 'Nike TechKnit Ultra, bölgesel havalandırma ve vücut haritalama teknolojisiyle antrenman performansınızı artırır.', '<p>Nike Dri-FIT ADV teknolojisi ile üretilen bu tişört, terleyen bölgeleri tespit ederek ekstra nefes alabilirlik sağlar. Vücut haritalama dikişleri sürtünmeyi en aza indirerek uzun koşularda konforu korur.</p><ul><li>Dri-FIT ADV nem yönetim teknolojisi</li><li>Bölgesel havalandırma panelleri</li><li>Hafif, esnek polyester karışımı</li><li>Slim fit kesim</li><li>Yıkamaya dayanıklı baskı</li></ul>', 1299.00, NULL, 230, 'NKE-TSH-DFTKU', 'Nike', 11, 0.00, 0, TRUE, FALSE, '["nike","tişört","spor","dri-fit","antrenman"]', 'Nike Dri-FIT ADV', 'Sporcular İçin Fonksiyonel Tişört', NOW()),
(51, 'Adidas Originals Trefoil Logo Erkek Tişört Beyaz', 'adidas-originals-trefoil-tisort-beyaz', 'Adidas Originals ikonik üç yaprak logosuyla günlük kullanım için klasik ve şık bir sokak stili tişörttür.', '<p>Adidas Originals koleksiyonunun vazgeçilmezi olan bu tişört, %100 pamuk dokusuyla nefes alabilir ve gün boyu konforlu bir his sunar. Oversized kesim tüm vücut tiplerine uyum sağlar.</p><ul><li>%100 organik pamuk</li><li>Ikonik Trefoil logosu</li><li>Regular/Oversize fit</li><li>Bisiklet yaka</li><li>Makine yıkamaya uygun</li></ul>', 899.00, NULL, 345, 'ADI-TSH-TRFWHT', 'Adidas', 11, 0.00, 0, TRUE, FALSE, '["adidas","originals","tişört","günlük","pamuk"]', 'Adidas Originals Trefoil', 'Klasik Sokak Stili', NOW()),
(52, 'Levi''s Vintage Graphic Tee 501 Logolu Tişört', 'levis-vintage-graphic-tee-501', 'Levi''s ikonik 501 grafik baskısıyla bu tişört, retro estetiği modern kesimle buluşturuyor.', '<p>Levi''s Vintage koleksiyonundan bu tişört, ağartılmış efekt ve eskitilmiş baskı tekniğiyle 90ların ruhunu yeniden yorumlar. Rahat regular fit kesim her gün kullanıma uygundur.</p><ul><li>%100 pamuk ringspun dokuma</li><li>Vintage wash efekti</li><li>Grafik logo baskı, solmaya dayanıklı</li><li>Regular fit, yuvarlak yaka</li><li>Unisex tasarım</li></ul>', 749.00, NULL, 189, 'LVS-TSH-VNT501', 'Levi''s', 11, 0.00, 0, TRUE, FALSE, '["levis","tişört","vintage","graphic","pamuk"]', 'Levi''s Vintage Graphic Tee', 'Retro Esintili Günlük Stil', NOW()),
(53, 'Tommy Hilfiger Slim Fit Flag Logo Polo Tişört', 'tommy-hilfiger-slim-fit-polo-flag', 'Tommy Hilfiger''ın ikonik bayrak logosuyla klasik polo tişört, iş casual ve hafta sonu kombinlerinde şıklık sunar.', '<p>Tommy Hilfiger imzası taşıyan bu polo tişört, pima pamuk dokusunun yumuşaklığını ve nefes alabilirliğini slim fit kesimle buluşturur. Her mevsim kullanılabilir hafifliği ve görünüşüyle gardırobun temel parçalarından biridir.</p><ul><li>%100 Pima pamuk</li><li>Slim fit kesim</li><li>Örgü polo yaka</li><li>Ikonik bayrak logo nakış</li><li>2 düğmeli plaketi</li></ul>', 1199.00, NULL, 167, 'TMH-TSH-SLFPOL', 'Tommy Hilfiger', 11, 0.00, 0, TRUE, FALSE, '["tommy hilfiger","polo","tişört","klasik","pamuk"]', 'Tommy Hilfiger Polo', 'Şık ve Rahat Polo Yaka', NOW()),
(54, 'Under Armour HeatGear Compression Tişört Erkek', 'under-armour-heatgear-compression-tisort', 'Under Armour HeatGear Compression, vücudu serin tutan ve yorgunluğu azaltan yüksek performans antrenman tişörtü.', '<p>Under Armour HeatGear teknolojisi, yoğun antrenmanlar sırasında vücudun sıcaklığını düzenler ve ter nemini uzak tutar. 4 yönlü streç kumaş tam hareket özgürlüğü sağlar.</p><ul><li>HeatGear nem kontrol teknolojisi</li><li>4 yönlü streç kumaş</li><li>Kompresyon fit, kas desteği</li><li>UPF 30+ güneş koruması</li><li>Antikoku teknolojisi</li></ul>', 1099.00, NULL, 211, 'UAR-TSH-HGCOMP', 'Under Armour', 11, 0.00, 0, TRUE, FALSE, '["under armour","compression","spor tişört","heatgear","antrenman"]', 'UA HeatGear Compression', 'Yüksek Performanslı Termal Tişört', NOW()),

-- GİYİM - SWEATSHİRT (12)
(55, 'Nike Tech Fleece Erkek Sweatshirt Gri', 'nike-tech-fleece-erkek-sweatshirt-gri', 'Nike Tech Fleece, hafif termal teknolojisi ile ısı yalıtımı sağlarken hacimsiz bir görünüm sunar.', '<p>Nike Tech Fleece, çift katmanlı termal yapısıyla soğuk havalarda sizi sıcak tutar; ancak geleneksel sweatshirtlerin ağırlığını taşımaz. Şehirden spor sahasına kadar her ortamda rahatlıkla kullanılabilir.</p><ul><li>Nike Tech Fleece çift katmanlı kumaş</li><li>Termal yalıtım, hafif yapı</li><li>Fermuarlı ön cep, kapüşon</li><li>Ribana bileklik ve bel bandı</li><li>%66 pamuk, %34 polyester</li></ul>', 3499.00, NULL, 156, 'NKE-SWT-TFLCGR', 'Nike', 12, 0.00, 0, TRUE, FALSE, '["nike","tech fleece","sweatshirt","kapüşonlu","spor"]', 'Nike Tech Fleece Sweatshirt', 'Hafif Isı Yalıtımı ve Stil', NOW()),
(56, 'Champion Reverse Weave Hoodie Lacivert', 'champion-reverse-weave-hoodie-lacivert', 'Champion''ın ikonik Reverse Weave dokuma teknolojisiyle bu hoodie yıkama sonrası şeklini korur.', '<p>Champion Reverse Weave teknolojisi, yatay yerine dikey dokuması sayesinde yıkamadan sonra çekmeyi ve şekil bozulmasını engeller. 90ların kolej stilini modern kesimle yeniden yorumlar.</p><ul><li>Reverse Weave shrink-resistant dokuma</li><li>%82 pamuk, %18 polyester</li><li>Kanguru cep, ayarlanabilir ipli kapüşon</li><li>Ikonik C logosu nakış</li><li>Regular fit, ağır gramaj</li></ul>', 1999.00, NULL, 134, 'CHP-SWT-RVWHDN', 'Champion', 12, 0.00, 0, TRUE, FALSE, '["champion","hoodie","sweatshirt","reverse weave","kolej"]', 'Champion Reverse Weave', 'Formunu Koruyan İkonik Hoodie', NOW()),
(57, 'Adidas Essentials Fleece 3-Stripes Erkek Sweatshirt', 'adidas-essentials-fleece-3stripes-sweatshirt', 'Adidas klasik 3 çizgi tasarımıyla bu sweatshirt, günlük konfor ve ikonik spor stilini birleştirir.', '<p>Adidas Essentials koleksiyonunun vazgeçilmezi olan bu sweatshirt, yumuşak fleece dokusunu temiz Adidas estetiğiyle buluşturur. Eğitimden sokağa her ortama uyum sağlayan çok yönlü bir tasarımdır.</p><ul><li>Yumuşak fleece iç yüzey</li><li>%70 pamuk, %30 dönüştürülmüş polyester</li><li>3-stripes kol şeridi</li><li>Ribana yakalık, bileklik, bel</li><li>Regular fit</li></ul>', 1599.00, NULL, 198, 'ADI-SWT-ESS3STR', 'Adidas', 12, 0.00, 0, TRUE, FALSE, '["adidas","sweatshirt","3 çizgi","fleece","günlük"]', 'Adidas Essentials Sweatshirt', 'Geleneksel Adidas Spor Stili', NOW()),
(58, 'Stüssy Stock Logo Crew Sweatshirt Krem', 'stussy-stock-logo-crew-sweatshirt-krem', 'Stüssy''nin imza yazı tipiyle bu crew neck sweatshirt, streetwear kültürünün sembolü olmaya devam ediyor.', '<p>Stüssy Stock Logo sweatshirt, kalın pamuklu fransız havlu dokusunu ikonik Stüssy yazı tipiyle buluşturur. Oversized kesim ve drop shoulder detayı modern sokak stilini tamamlar.</p><ul><li>%100 ağır gramaj pamuk, Fransız havlu içi</li><li>Ikonik Stüssy logo baskı</li><li>Oversized, drop shoulder kesim</li><li>Ribana yakalık ve bileklik</li><li>Unisex tasarım</li></ul>', 2799.00, NULL, 89, 'STU-SWT-STKLGCR', 'Stüssy', 12, 0.00, 0, TRUE, FALSE, '["stussy","sweatshirt","streetwear","crew neck","logo"]', 'Stüssy Stock Logo Crew', 'Modern Sokak Tarzı Sembolü', NOW()),
(59, 'The North Face Tekno Logo Hoodie Siyah', 'the-north-face-tekno-logo-hoodie-siyah', 'The North Face Tekno Hoodie, dağdan şehre her ortamda kullanılabilecek fonksiyonel bir sweatshirt.', '<p>The North Face Tekno Hoodie, geri dönüştürülmüş polyester fleece ile üretilmiştir; hem çevreye duyarlı hem de olağanüstü sıcak tutar. Reflektif TNF logosu düşük ışık koşullarında görünürlük sağlar.</p><ul><li>%100 geri dönüştürülmüş polyester fleece</li><li>Reflektif logo detayı</li><li>Önden fermuarlı kangaroo cep</li><li>Ayarlanabilir kapüşon</li><li>Bluesign® onaylı kumaş</li></ul>', 3199.00, NULL, 102, 'TNF-SWT-TKNHDN', 'The North Face', 12, 0.00, 0, TRUE, FALSE, '["the north face","hoodie","sweatshirt","outdoor","fleece"]', 'TNF Tekno Logo Hoodie', 'Çevre Dostu Sıcaklık ve Konfor', NOW()),

-- GİYİM - PANTOLON (13)
(60, 'Levi''s 501 Original Fit Erkek Kot Pantolon Koyu Indigo', 'levis-501-original-fit-kot-pantolon', 'Levi''s 501, 1873''ten bu yana değişmeyen kalıbıyla denim tarihinin en ikonik pantolonu olmaya devam ediyor.', '<p>Levi''s 501 Original Fit, straight leg kesimi ve düğmeli ön kapama detayıyla denim kültürünü şekillendirmiştir. Stonewashed koyu indigo rengi klasik bir görünüm sunarken her yıkamada doğal bir eskime tonu kazanır.</p><ul><li>%100 pamuk denim, 12.5 oz</li><li>Straight leg, regular bel kesim</li><li>Düğmeli fly kapama</li><li>Stonewashed koyu indigo</li><li>Beş cep klasik tasarım</li></ul>', 1799.00, NULL, 267, 'LVS-PNT-501OFD', 'Levi''s', 13, 0.00, 0, TRUE, FALSE, '["levis","jean","pantolon","denim","501"]', 'Levi''s 501 Original Fit', 'Denim Dünyasının Klasik İkonu', NOW()),
(61, 'Carhartt WIP Sid Pant Chino Haki', 'carhartt-wip-sid-pant-chino-haki', 'Carhartt WIP Sid Pant, sade kesimi ve dayanıklı pamuklu dokuma ile çok yönlü günlük kullanım pantolonu.', '<p>Carhartt iş pantolonu kalitesini streetwear estetiğiyle harmanlayan Sid Pant, ince bel bağı ve yan cepleriyle casual-smart kombinlere uyum sağlar. Sıkı ripstop pamuk dokusu uzun süre şeklini korur.</p><ul><li>%98 pamuk, %2 elastan</li><li>Slim fit, tapered bacak</li><li>Elastik bel bandı + iç bağ</li><li>Haki (Leather tint)</li><li>Carhartt WIP etiket detayı</li></ul>', 2199.00, NULL, 143, 'CRH-PNT-SIDCHI', 'Carhartt', 13, 0.00, 0, TRUE, FALSE, '["carhartt","chino","pantolon","günlük","slim"]', 'Carhartt WIP Sid Pant', 'Streetwear Estetiğinde Chino', NOW()),
(62, 'Nike Sportswear Tech Fleece Jogger Erkek Eşofman Altı', 'nike-tech-fleece-jogger-esofman', 'Nike Tech Fleece Jogger, termal konforu modern jogger siluetiyle birleştiren şehirli antrenman pantolonu.', '<p>Nike Tech Fleece kumaşı, çift katmanlı yapısıyla minimum hacimde maksimum ısı yalıtımı sağlar. Tapered paça ve elastik bileklik şık bir siluet oluştururken ribana bel bandı mükemmel uyum sağlar.</p><ul><li>Nike Tech Fleece çift katmanlı kumaş</li><li>Elastik bel + iç ayar bağı</li><li>Derin yan cepler + fermuarlı cep</li><li>Tapered fit, ribana bileklik</li><li>%66 pamuk, %34 polyester</li></ul>', 2999.00, NULL, 178, 'NKE-PNT-TFLCJG', 'Nike', 13, 0.00, 0, TRUE, FALSE, '["nike","tech fleece","jogger","eşofman","spor"]', 'Nike Tech Fleece Jogger', 'Modern Jogger Silueti', NOW()),
(63, 'Dickies 874 Original Work Pant Siyah', 'dickies-874-original-work-pant-siyah', 'Dickies 874, onlarca yıldır değişmeyen straight-fit siluetiyle workwear ve streetwear dünyasının favorisi.', '<p>Dickies 874, polyester-pamuk karışımı kıvrak dokusuyla hem sağlam hem de rahat bir pantolon sunar. Streetwear markalarının koleksiyonlarına ilham kaynağı olan kesimi, günlük ve iş ortamlarına eşit uyum sağlar.</p><ul><li>%65 polyester, %35 pamuk twill</li><li>Straight fit, orta bel</li><li>Wrinkle ve stain resistant</li><li>Siyah, koyu renk seçenekleri</li><li>Klasik beş cep + yan cep</li></ul>', 1099.00, NULL, 312, 'DCK-PNT-874WRK', 'Dickies', 13, 0.00, 0, TRUE, FALSE, '["dickies","874","workwear","pantolon","streetwear"]', 'Dickies 874 Work Pant', 'Dayanıklı ve İkonik İş Pantolonu', NOW()),
(64, 'Columbia Silver Ridge Convertible Pant Erkek Outdoor', 'columbia-silver-ridge-convertible-pant', 'Columbia Silver Ridge, fermuar ile şorta dönüşen çift işlevli yapısı ve UPF 50 korumasıyla outdoor için ideal.', '<p>Columbia Silver Ridge Convertible Pant, hafif omni-shade nylon dokusuyla güneş koruması sağlarken bacak bölümü fermuarla sökülerek şorta dönüşür. Nem yönetim sistemi trekking ve kamp aktivitelerinde üstün konfor sunar.</p><ul><li>UPF 50 güneş koruması</li><li>Omni-Shade ve Omni-Wick teknolojisi</li><li>Fermuar ile şorta çevrilebilir</li><li>Takviyeli diz ve oturma bölgesi</li><li>Hızlı kuruyan hafif nylon</li></ul>', 1899.00, NULL, 97, 'CLB-PNT-SRVCON', 'Columbia', 13, 0.00, 0, TRUE, FALSE, '["columbia","outdoor","pantolon","dönüştürülebilir","trekking"]', 'Columbia Silver Ridge', 'Çift İşlevli Outdoor Pantolonu', NOW()),

-- AYAKKABI - SPOR AYAKKABI (15)
(65, 'Nike Air Max 270 Erkek Spor Ayakkabı Siyah/Beyaz', 'nike-air-max-270-siyah-beyaz', 'Air Max 270, 270 derecelik Air ünite yastıklamasıyla Nike''ın en büyük topuk havasını sunan lifestyle modeli.', '<p>Nike Air Max 270, günlük kullanım için tasarlanmış olsa da maksimum topuk Air ünite ile uzun süre giyildiğinde bile üstün konfor sağlar. Mühendislik örgüsü üst kısım hafiflik ve nefes alabilirlik sağlarken stilini tamamlar.</p><ul><li>270° görünür Air ünite topuk yastıklama</li><li>Mühendislik örgüsü üst</li><li>Kauçuk taban, dayanıklı alt yüzey</li><li>Bağcıklı kapama</li><li>Erkek numaralama: 40-46</li></ul>', 5499.00, NULL, 134, 'NKE-SNK-AM270BW', 'Nike', 15, 0.00, 0, TRUE, FALSE, '["nike","air max","spor ayakkabı","270","lifestyle"]', 'Nike Air Max 270', 'Hava Yastıklı Günlük Konfor', NOW()),
(66, 'Adidas Ultraboost 22 Erkek Koşu Ayakkabısı Beyaz', 'adidas-ultraboost-22-erkek-beyaz', 'Ultraboost 22, BOOST ara taban teknolojisi ve Primeknit+ üst yüzeyi ile koşularda üstün enerji geri dönüşü sağlar.', '<p>Adidas Ultraboost 22, her adımda enerjinizi geri veren BOOST ara taban ve ayağınıza oturan Primeknit+ kumaş ile maraton antrenmanlarından günlük kullanıma kadar mükemmeldir. Continental™ lastik taban yüzey tutuşunu artırır.</p><ul><li>BOOST ara taban, maksimum enerji iadesi</li><li>Primeknit+ esnek üst kısım</li><li>Continental™ lastik dış taban</li><li>Linear Energy Push sistemi</li><li>%50 geri dönüştürülmüş malzeme</li></ul>', 6999.00, NULL, 98, 'ADI-SNK-UB22WHT', 'Adidas', 15, 0.00, 0, TRUE, FALSE, '["adidas","ultraboost","koşu","boost","spor ayakkabı"]', 'Adidas Ultraboost 22', 'Üstün Enerji Geri Dönüşümlü Koşu Ayakkabısı', NOW()),
(67, 'New Balance 990v6 Made in USA Gri', 'new-balance-990v6-made-in-usa-gri', 'New Balance 990v6, ABD''de üretilen ENCAP ara taban teknolojisi ve premium süet üstle 40 yıllık mirasını sürdürüyor.', '<p>New Balance 990v6, premium süet ve mesh kombinasyonu üst kısım ve ENCAP ara taban teknolojisiyle hem estetik hem de fonksiyonel mükemmelliği sunar. Made in USA kalitesi ve dayanıklılığı ile yatırım değeri taşıyan bir ayakkabı.</p><ul><li>ENCAP ara taban: EVA + poliüretan çerçeve</li><li>Premium süet ve mesh üst</li><li>Blended gum/siyah dış taban</li><li>Made in USA</li><li>Düz tabanlı, geniş fit</li></ul>', 8999.00, NULL, 45, 'NBL-SNK-990V6GR', 'New Balance', 15, 0.00, 0, TRUE, FALSE, '["new balance","990","made in usa","spor ayakkabı","süet"]', 'New Balance 990v6', 'Premium Kalitede Retro Sneaker', NOW()),
(68, 'ASICS Gel-Kayano 30 Koşu Ayakkabısı Erkek', 'asics-gel-kayano-30-erkek', 'Gel-Kayano 30, 30. yıl özel tasarımı ve FF BLAST+ ECO köpüğüyle destekli koşuculara üstün stabilite sunar.', '<p>ASICS Gel-Kayano 30, FF BLAST+ ECO geri dönüştürülmüş köpük ara taban ve PureGEL teknolojisiyle her koşuda mükemmel zemin adaptasyonu sağlar. LITETRUSS iç desteği aşırı içe dönüşü önler ve sağlıklı koşu formu destekler.</p><ul><li>FF BLAST+ ECO geri dönüştürülmüş köpük</li><li>PureGEL topuk yastıklama</li><li>LITETRUSS medial destek</li><li>Engineered Knit Jacquard üst</li><li>Erkek: 40-47 beden</li></ul>', 7499.00, NULL, 73, 'ACS-SNK-GK30M', 'ASICS', 15, 0.00, 0, TRUE, FALSE, '["asics","gel-kayano","koşu","stabilite","spor ayakkabı"]', 'ASICS Gel-Kayano 30', 'Stabilite ve Yastıklama Uzmanı', NOW()),
(69, 'Salomon Speedcross 6 GTX Erkek Trail Koşu', 'salomon-speedcross-6-gtx-erkek', 'Speedcross 6 GTX, Gore-Tex membranı ve agresif çivi dizilimi ile zorlu arazilerde güvenli tutuş sağlayan trail koşu ayakkabısı.', '<p>Salomon Speedcross 6 GTX, GORE-TEX Extended Comfort su geçirmezliği ve Contagrip® dış tabanıyla ıslak ve çamurlu arazilerde mükemmel performans sunar. EnergyCell+ ara taban ise uzun parkurlarda yorulmadan koşmayı destekler.</p><ul><li>GORE-TEX Extended Comfort membran</li><li>Contagrip® agresif dış taban</li><li>EnergyCell+ ara taban köpüğü</li><li>Hızlı bağlama Quicklace sistemi</li><li>Sentetik + tekstil üst</li></ul>', 8199.00, NULL, 56, 'SLM-SNK-SC6GTX', 'Salomon', 15, 0.00, 0, TRUE, FALSE, '["salomon","speedcross","trail","gore-tex","outdoor ayakkabı"]', 'Salomon Speedcross 6 GTX', 'Zorlu Arazi ve Hava Koşulları İçin', NOW()),

-- AYAKKABI - SNEAKER (16)
(70, 'Adidas Stan Smith Vegan Beyaz/Yeşil', 'adidas-stan-smith-vegan-beyaz-yesil', 'Adidas Stan Smith Vegan, bitkisel kaynaklı malzemeler kullanılarak üretilen ikonik tenis sneaker''ının sürdürülebilir versiyonu.', '<p>1971''den bu yana tarz ikonunun vegan versiyonu olan Stan Smith, üretiminde hayvansal ürün kullanmaz. Mylo™ mantar deri ve geri dönüştürülmüş içerik ile hem stylish hem de çevre dostu bir seçim sunar.</p><ul><li>Hayvansal ürün içermez (Vegan)</li><li>Mylo™ mantar kaynaklı deri üst</li><li>%50 geri dönüştürülmüş EVA ara taban</li><li>Perforasyonlu üç çizgi detayı</li><li>Klasik tennis low-top silüet</li></ul>', 3999.00, NULL, 167, 'ADI-SNK-SSMVGN', 'Adidas', 16, 0.00, 0, TRUE, FALSE, '["adidas","stan smith","vegan","sneaker","klasik"]', 'Adidas Stan Smith Vegan', 'Sürdürülebilir ve İkonik Tenis Sneaker', NOW()),
(71, 'Converse Chuck Taylor All Star High Top Siyah', 'converse-chuck-taylor-all-star-high-top', 'Chuck Taylor All Star, 1917''den bu yana değişmeyen tuval üst ve vulkanize kauçuk taban ile evergreen sneaker ikonu.', '<p>Converse Chuck Taylor All Star High Top, 100 yılı aşkın süredir aynı kalıpta üretilmeye devam eden ve pop kültürün ayrılmaz parçası haline gelen ikonik high-top sneaker''dır. Sade siyah tuval herhangi bir kombin ile uyum sağlar.</p><ul><li>%95 pamuk tuval üst</li><li>Vulkanize kauçuk taban</li><li>Optik beyaz kenar bant</li><li>Ankle patch All Star logosu</li><li>Unisex, geniş beden aralığı</li></ul>', 2299.00, NULL, 289, 'CNV-SNK-CTASHI', 'Converse', 16, 0.00, 0, TRUE, FALSE, '["converse","chuck taylor","high top","sneaker","klasik"]', 'Chuck Taylor High Top', 'Evrensel Sneaker İkonu', NOW()),
(72, 'New Balance 550 Beyaz/Krem Retro Sneaker', 'new-balance-550-beyaz-krem-retro', 'New Balance 550, 80lerin basketbol estetiğini modern günlük kullanım anlayışıyla yeniden yorumlayan retro sneaker.', '<p>New Balance 550, orijinal 1989 basketbol ayakkabısından ilham alarak tasarlanmıştır. Temiz deri üst ve kalın EVA ara taban, hem retro tutkunlarına hem de minimal stil arayanlarına hitap eder.</p><ul><li>Tam tahıl deri üst</li><li>Belirgin kalın EVA ara taban</li><li>Ortopedik iç tabanlık</li><li>Klasik "N" logosu yan detay</li><li>Düşük bileklik, court silüeti</li></ul>', 4299.00, NULL, 121, 'NBL-SNK-550WCR', 'New Balance', 16, 0.00, 0, TRUE, FALSE, '["new balance","550","retro","sneaker","deri"]', 'New Balance 550 Retro', '80ler Basketbol Estetiği', NOW()),
(73, 'Vans Old Skool Checkerboard Siyah/Beyaz', 'vans-old-skool-checkerboard', 'Vans Old Skool Checkerboard, skate kültürünün sembolü olan Sidestripe ve dama deseniyle ölümsüz bir klasik.', '<p>Vans Old Skool, 1977''de ilk kez piyasaya çıktığında skate ayakkabılarına yeni bir boyut katan ikonik Sidestripe detayını taşır. Checkerboard dama deseni ise subkültür tarzını her zamankinden daha cesur bir şekilde ifade eder.</p><ul><li>Tuval ve süet kombinasyon üst</li><li>Dama desenli checkerboard baskı</li><li>Ikonik Vans Sidestripe</li><li>UltraCush Lite iç tabanlık</li><li>Vulkanize dış taban, skate grip</li></ul>', 2799.00, NULL, 203, 'VNS-SNK-OSKCBW', 'Vans', 16, 0.00, 0, TRUE, FALSE, '["vans","old skool","checkerboard","skate","sneaker"]', 'Vans Old Skool Checkerboard', 'Skate Kültürünün İkonik Sembolü', NOW()),
(74, 'Puma Suede Classic XXI Erkek Sneaker Lacivert', 'puma-suede-classic-xxi-lacivert', 'Puma Suede Classic XXI, 1968''den bu yana değişmeyen süet üst ve Formstrip detayıyla zamansız spor estetiğini yaşatır.', '<p>Puma Suede, onlarca yıl boyunca hip-hop, breakdance ve sokak kültürünün vazgeçilmez parçası olmuş ikonik süet sneaker''dır. Classic XXI versiyonu, özel kauçuk çıkıntı ve hafıza köpüğü iç tabanlıkla modern konfor katar.</p><ul><li>Yüksek kalite süet üst kısım</li><li>Ikonik Puma Formstrip detayı</li><li>Hafıza köpüğü iç tabanlık</li><li>EVA ara taban yastıklama</li><li>Kauçuk dış taban çıkıntısı</li></ul>', 2499.00, NULL, 178, 'PMA-SNK-SUECLNV', 'Puma', 16, 0.00, 0, TRUE, FALSE, '["puma","suede","sneaker","klasik","lifestyle"]', 'Puma Suede Classic XXI', 'Hip-Hop ve Sokak Kültürü Mirası', NOW()),

-- EV & YAŞAM (4)
(75, 'Philips Hue Starter Kit E27 Akıllı LED Ampul 3lü Set', 'philips-hue-starter-kit-e27-3lu', 'Philips Hue Starter Kit, akıllı ev aydınlatmasına başlamak için ihtiyaç duyulan her şeyi tek pakette sunar.', '<p>Philips Hue Starter Kit, 16 milyondan fazla renk seçeneği ve kısılabilir beyaz ışık aralığıyla evinizin her köşesini kişiselleştirmenizi sağlar. Hue Bridge ile Alexa, Google Assistant ve Apple HomeKit ile tam entegrasyon sunar.</p><ul><li>3 adet E27 Beyaz ve Renkli ampul</li><li>1 Hue Bridge dahil</li><li>16 milyon+ renk seçeneği</li><li>Alexa, Google, HomeKit uyumlu</li><li>Uygulama ile zamanlama ve sahne kurma</li></ul>', 3999.00, NULL, 89, 'PHL-HOM-HUESKITE', 'Philips', 4, 0.00, 0, TRUE, FALSE, '["philips hue","akıllı ev","led","aydınlatma","smart home"]', 'Philips Hue Starter Kit', 'Akıllı Ev Aydınlatmasına Giriş', NOW()),
(76, 'Dyson V15 Detect Absolute Kablosuz Süpürge', 'dyson-v15-detect-absolute-kablosuz', 'Dyson V15 Detect, lazer tozunu görünür kılan teknolojisi ve otomatik güç ayarıyla temizliği bilimsel kesinliğe taşır.', '<p>Dyson V15 Detect''in yeşil lazer ışını, zeminlerde gözle görülemeyen tozu görünür hale getirerek hiç atlamadan temizlik yapmanızı sağlar. HEPA filtrasyon sistemi tüm partikülleri hapseder ve temiz hava üfler.</p><ul><li>Lazer toz tespit teknolojisi</li><li>60 dakikaya kadar pil ömrü</li><li>HEPA filtreli 99.99% parçacık yakalama</li><li>Akustik piezo sensörle otomatik güç</li><li>LCD ekran, gerçek zamanlı performans</li></ul>', 18999.00, NULL, 34, 'DYS-HOM-V15ABSL', 'Dyson', 4, 0.00, 0, TRUE, FALSE, '["dyson","süpürge","kablosuz","v15","akıllı ev"]', 'Dyson V15 Detect Absolute', 'Görünmeyen Tozları Görünür Kılan Temizlik', NOW()),
(77, 'Le Creuset Signature Döküm Demir Tencere 26cm Kırmızı', 'le-creuset-signature-dokum-demir-tencere-26cm', 'Le Creuset 26cm döküm demir tencere, eşsiz ısı dağılımı ve renk seçenekleriyle mutfakta hem estetik hem işlevsel.', '<p>Le Creuset Signature serisi döküm demir tencere, 90 yılı aşkın Fransız mühendislik geleneğini yansıtır. Eşsiz emaye kaplama sayesinde asit içeren gıdalarla bile güvenle kullanılabilir ve çıtır altın oluşturmada rakipsizdir.</p><ul><li>%100 döküm demir gövde</li><li>Vibrant Flame kırmızı emaye kaplama</li><li>Fırın güvenli 260°C''ye kadar</li><li>Tüm ocak tiplerinde kullanım (indüksiyon dahil)</li><li>Ömür boyu garanti</li></ul>', 8999.00, NULL, 28, 'LCR-HOM-SDTMKRM', 'Le Creuset', 4, 0.00, 0, TRUE, FALSE, '["le creuset","tencere","döküm","mutfak","emaye"]', 'Le Creuset Signature Tencere', 'Fransız Mutfağı Geleneği', NOW()),
(78, 'Nespresso Vertuo Next Premium Kahve Makinesi', 'nespresso-vertuo-next-premium-kahve-makinesi', 'Nespresso Vertuo Next, Centrifusion teknolojisi ve 5 farklı kahve boyutu seçeneğiyle barista kalitesinde ev kahvesi sunar.', '<p>Nespresso Vertuo Next''in Centrifusion™ teknolojisi, kapsülü saniyede 7000 kez döndürerek mükemmel crema tabakası oluşturur. Bluetooth bağlantısı ve Nespresso uygulaması ile kahve kapsülü siparişi ve makine ayarları tek ekranda yönetilir.</p><ul><li>Centrifusion™ barcode okuma teknolojisi</li><li>5 kahve boyutu: Espresso – Alto XL</li><li>15 saniyede ön ısınma</li><li>Wi-Fi + Bluetooth bağlantısı</li><li>1.1 lt su haznesi</li></ul>', 4999.00, NULL, 67, 'NSP-HOM-VTNXPRM', 'Nespresso', 4, 0.00, 0, TRUE, FALSE, '["nespresso","kahve makinesi","vertuo","kapsül","ev"]', 'Nespresso Vertuo Next', 'Barista Kalitesinde Ev Kahvesi', NOW()),
(79, 'IKEA KALLAX Kitaplık/Raf Ünitesi 4x4 Beyaz', 'ikea-kallax-kitaplik-raf-unitesi-4x4', 'IKEA KALLAX, çok yönlü modüler yapısıyla kitaplık, kayıt koleksiyonu dolabı veya oda bölücü olarak kullanılabilir.', '<p>IKEA KALLAX, zarif dikdörtgen gözenekli tasarımı ve geniş aksesuar yelpazesiyle istediğiniz düzenlemeye uyum sağlar. Kapılar, çekmeceler ve kasa kutuları ile kişiselleştirilebilen çok işlevli bir raf sistemidir.</p><ul><li>16 gözeli 4x4 konfigürasyon</li><li>Lamine parçacık levhası, beyaz kaplama</li><li>Duvara sabitleme aparatı dahil</li><li>Maksimum 13 kg/göz yük kapasitesi</li><li>Kapı ve çekmece aksesuar uyumlu</li></ul>', 4499.00, NULL, 43, 'IKA-HOM-KLX44WH', 'IKEA', 4, 0.00, 0, TRUE, FALSE, '["ikea","kallax","kitaplık","raf","ev mobilya"]', 'IKEA KALLAX Kitaplık', 'Çok Yönlü Modüler Kitaplık', NOW()),

-- SPOR & OUTDOOR (5)
(80, 'Garmin Forerunner 965 Koşu GPS Akıllı Saat', 'garmin-forerunner-965-gps-saat', 'Garmin Forerunner 965, AMOLED ekran ve gelişmiş koşu dinamikleri ile yarı maraton ve maraton koşucuları için en kapsamlı GPS saati.', '<p>Garmin Forerunner 965, Training Readiness skoru ve HRV Status ile antrenman yükünüzü akıllıca yönetmenizi sağlar. Titanium çerçeve ve Corning® Gorilla® Glass DX ile dayanıklılık ve estetik bir arada sunulur.</p><ul><li>AMOLED dokunmatik ekran</li><li>Çok bant GPS + GLONASS + Galileo</li><li>Training Readiness ve HRV Status</li><li>31 saate kadar GPS pil ömrü</li><li>Titanium çerçeve, 10 ATM su direnci</li></ul>', 13999.00, NULL, 38, 'GRM-SPT-FR965TI', 'Garmin', 5, 0.00, 0, TRUE, FALSE, '["garmin","forerunner","gps saat","koşu","akıllı saat"]', 'Garmin Forerunner 965', 'Kapsamlı Koşu Dinamikleri Saati', NOW()),
(81, 'Decathlon Quechua MH500 Trekking Sırt Çantası 40L', 'decathlon-quechua-mh500-trekking-canta-40l', 'Quechua MH500 40L, hava sirkülasyonlu sırt paneli ve yağmur kılıfıyla uzun günlük trekkingler için ideal.', '<p>Decathlon Quechua MH500, 40 litrelik hacmi ve anatomik omuz askı sistemiyle ağırlığı vücutta dengeli dağıtır. Fresh Flex hava sirkülasyonlu sırt paneli, sıcak havalarda bile vücutla çantanın arasında hava akışı sağlar.</p><ul><li>40 litrelik hacimlendirilebilir ana bölme</li><li>Fresh Flex hava sirkülasyonlu sırt</li><li>Entegre yağmur kılıfı</li><li>Hidrasyon sistemi uyumlu (2L)</li><li>Hip belt ve sternum straps</li></ul>', 1899.00, NULL, 112, 'DCT-SPT-MH500BG', 'Quechua', 5, 0.00, 0, TRUE, FALSE, '["quechua","decathlon","trekking","sırt çantası","outdoor"]', 'Quechua MH500 Sırt Çantası', 'Hava Sirkülasyonlu Trekking Çantası', NOW()),
(82, 'Black Diamond Spot 400 Kafa Feneri', 'black-diamond-spot-400-kafa-feneri', 'Black Diamond Spot 400, IPX8 su geçirmezliği ve 400 lümen ile kamp, tırmanış ve koşu aktiviteleri için güvenilir kafa lambası.', '<p>Black Diamond Spot 400, PowerTap™ teknolojisiyle dokunuşla yüksek ve düşük ışık modları arasında geçiş yapmanızı sağlar. Kırmızı gece görüş modu ve kilitleme özelliği kaza ile açılmayı önler.</p><ul><li>400 lümen maksimum çıkış</li><li>PowerTap™ kısma teknolojisi</li><li>IPX8 su geçirmezlik</li><li>Kırmızı gece görüş modu</li><li>3 AAA pil, 200 saate kadar</li></ul>', 1299.00, NULL, 167, 'BLD-SPT-SP400HL', 'Black Diamond', 5, 0.00, 0, TRUE, FALSE, '["black diamond","kafa feneri","kamp","outdoor","tırmanış"]', 'Black Diamond Spot 400', 'Güçlü ve Su Geçirmez Kafa Feneri', NOW()),
(83, 'Buff Lightweight Merino Wool Balaclava Yün Boyunluk', 'buff-lightweight-merino-wool-balaclava', 'Buff Merino Wool Balaclava, doğal Merino yününün termal ve nem yönetim özellikleriyle her mevsim boyunluk.', '<p>%100 Merino yünü ile üretilen Buff Balaclava, soğuk havalarda termal koruma sağlarken aşırı nemlenmeyi ve kötü kokuyu önleyen doğal özelliklere sahiptir. 12 farklı kullanım pozisyonu sunar.</p><ul><li>%100 Ekstra ince Merino yünü</li><li>Doğal antistatik ve antimikrobiyal</li><li>12 farklı kullanım şekli</li><li>Koku önleyici doğal özellik</li><li>Hand wash, yıkamaya dayanıklı</li></ul>', 899.00, NULL, 234, 'BFF-SPT-MWBALCV', 'Buff', 5, 0.00, 0, TRUE, FALSE, '["buff","merino","boyunluk","outdoor","kış"]', 'Buff Merino Wool Balaclava', 'Doğal Termal Koruma ve Konfor', NOW()),
(84, 'Osprey Daylite Plus 20L Günlük Sırt Çantası', 'osprey-daylite-plus-20l-gunluk-canta', 'Osprey Daylite Plus 20L, hafif ağırlığı ve ergonomik AirSpeed askı sistemiyle şehir içi ve doğa yürüyüşlerinde ideal günlük çanta.', '<p>Osprey Daylite Plus, markanın ikonik AirSpeed™ askı sistemini 20 litrelik günlük çanta formatına taşır. Laptop bölmesi, hidrasyon sistemi uyumu ve harness ekleme noktaları ile tam donanımlıdır.</p><ul><li>20 litrelik hacimlendirilebilir yapı</li><li>AirSpeed™ havalandırmalı sırt paneli</li><li>15 inç laptop bölmesi</li><li>Hidrasyon sistemi uyumlu</li><li>Bluesign® onaylı kumaş</li></ul>', 2799.00, NULL, 78, 'OSP-SPT-DLP20GN', 'Osprey', 5, 0.00, 0, TRUE, FALSE, '["osprey","sırt çantası","günlük","outdoor","hiking"]', 'Osprey Daylite Plus 20L', 'Hafif ve Ergonomik Günlük Çanta', NOW());

-- 2. Insert Images (Initial Unsplash URLs)
INSERT INTO product_images
  (product_id, image_url, alt_text, is_primary, sort_order)
VALUES
(35, 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&h=600&fit=crop', 'Samsung Galaxy S24 Ultra', TRUE, 1),
(36, 'https://images.unsplash.com/photo-1695048133142-1a20484429be?w=800&h=600&fit=crop', 'Apple iPhone 15 Pro', TRUE, 1),
(37, 'https://images.unsplash.com/photo-1574944985070-8f3ebc6b79d2?w=800&h=600&fit=crop', 'Xiaomi 14 Pro', TRUE, 1),
(38, 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&h=600&fit=crop', 'Google Pixel 8 Pro', TRUE, 1),
(39, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop', 'OnePlus 12', TRUE, 1),
(40, 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&h=600&fit=crop', 'Apple MacBook Pro 14 M3', TRUE, 1),
(41, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop', 'Lenovo ThinkPad X1 Carbon', TRUE, 1),
(42, 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&h=600&fit=crop', 'ASUS ROG Zephyrus G14', TRUE, 1),
(43, 'https://images.unsplash.com/photo-1593642634443-44adaa06623a?w=800&h=600&fit=crop', 'Dell XPS 15 OLED', TRUE, 1),
(44, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=600&fit=crop', 'Apple iPad Pro M2', TRUE, 1),
(45, 'https://images.unsplash.com/photo-1589739900243-4b52cd9b104e?w=800&h=600&fit=crop', 'Samsung Galaxy Tab S9+', TRUE, 1),
(46, 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&h=600&fit=crop', 'Lenovo Tab P12 Pro', TRUE, 1),
(47, 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&h=600&fit=crop', 'Sony WH-1000XM5', TRUE, 1),
(48, 'https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=800&h=600&fit=crop', 'Apple AirPods Pro 2', TRUE, 1),
(49, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop', 'Bose QuietComfort Ultra', TRUE, 1),
(50, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=600&fit=crop', 'Nike Dri-FIT Tişört', TRUE, 1),
(51, 'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&h=600&fit=crop', 'Adidas Originals Tişört', TRUE, 1),
(52, 'https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&h=600&fit=crop', 'Levis Vintage Tişört', TRUE, 1),
(53, 'https://images.unsplash.com/photo-1625910513823-2e4dd8c41c6b?w=800&h=600&fit=crop', 'Tommy Hilfiger Polo', TRUE, 1),
(54, 'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&h=600&fit=crop', 'Under Armour Compression Tişört', TRUE, 1),
(55, 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=600&fit=crop', 'Nike Tech Fleece Sweatshirt', TRUE, 1),
(56, 'https://images.unsplash.com/photo-1614975059251-992f11792b9f?w=800&h=600&fit=crop', 'Champion Reverse Weave Hoodie', TRUE, 1),
(57, 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&h=600&fit=crop', 'Adidas Essentials Sweatshirt', TRUE, 1),
(58, 'https://images.unsplash.com/photo-1620799139834-6b8f844fbe61?w=800&h=600&fit=crop', 'Stussy Stock Logo Sweatshirt', TRUE, 1),
(59, 'https://images.unsplash.com/photo-1604644401890-0bd678c83788?w=800&h=600&fit=crop', 'The North Face Hoodie', TRUE, 1),
(60, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=600&fit=crop', 'Levis 501 Kot Pantolon', TRUE, 1),
(61, 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&h=600&fit=crop', 'Carhartt WIP Chino', TRUE, 1),
(62, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'Nike Tech Fleece Jogger', TRUE, 1),
(63, 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&h=600&fit=crop', 'Dickies 874 Pantolon', TRUE, 1),
(64, 'https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=800&h=600&fit=crop', 'Columbia Silver Ridge Pantolon', TRUE, 1),
(65, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop', 'Nike Air Max 270', TRUE, 1),
(66, 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&h=600&fit=crop', 'Adidas Ultraboost 22', TRUE, 1),
(67, 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=800&h=600&fit=crop', 'New Balance 990v6', TRUE, 1),
(68, 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=600&fit=crop', 'ASICS Gel-Kayano 30', TRUE, 1),
(69, 'https://images.unsplash.com/photo-1551107696-a4b0c5a0d9a2?w=800&h=600&fit=crop', 'Salomon Speedcross 6 GTX', TRUE, 1),
(70, 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=800&h=600&fit=crop', 'Adidas Stan Smith Vegan', TRUE, 1),
(71, 'https://images.unsplash.com/photo-1494496195158-c3bc7b2f88a4?w=800&h=600&fit=crop', 'Converse Chuck Taylor High Top', TRUE, 1),
(72, 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=800&h=600&fit=crop', 'New Balance 550', TRUE, 1),
(73, 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&h=600&fit=crop', 'Vans Old Skool Checkerboard', TRUE, 1),
(74, 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&h=600&fit=crop', 'Puma Suede Classic XXI', TRUE, 1),
(75, 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop', 'Philips Hue Starter Kit', TRUE, 1),
(76, 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&h=600&fit=crop', 'Dyson V15 Detect', TRUE, 1),
(77, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop', 'Le Creuset Tencere', TRUE, 1),
(78, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&h=600&fit=crop', 'Nespresso Vertuo Next', TRUE, 1),
(79, 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&h=600&fit=crop', 'IKEA KALLAX Kitaplık', TRUE, 1),
(80, 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&h=600&fit=crop', 'Garmin Forerunner 965', TRUE, 1),
(81, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=600&fit=crop', 'Quechua MH500 Sırt Çantası', TRUE, 1),
(82, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop', 'Black Diamond Spot 400 Kafa Feneri', TRUE, 1),
(83, 'https://images.unsplash.com/photo-1549989476-69a92fa57c36?w=800&h=600&fit=crop', 'Buff Merino Wool Balaclava', TRUE, 1),
(84, 'https://images.unsplash.com/photo-1622260614153-03223fb72052?w=800&h=600&fit=crop', 'Osprey Daylite Plus 20L', TRUE, 1);

SET foreign_key_checks = 1;
