-- ShopAI E-Commerce — Extended Product Seed (25 Products)
-- V17: Seller ID 3 — Mixed Categories (Electronics, Clothing, Shoes, Home, Sport)
-- Security: MySQL 8 Compatible | UTF8MB4

SET NAMES utf8mb4;
SET foreign_key_checks = 0;

-- 1. Insert Products
INSERT INTO products 
  (id, name, slug, description, long_description, price, discounted_price, stock_quantity, sku, brand, category_id, rating_avg, rating_count, is_active, is_featured, tags, meta_title, meta_description, created_at)
VALUES

-- ELEKTRONİK - AKILLI TELEFONLAR (7) — 3 ürün
(85, 'Sony Xperia 1 VI 256GB Siyah', 'sony-xperia-1-vi-256gb-siyah', 'Sony Xperia 1 VI, 4K OLED ekranı ve Zeiss optikli kamera sistemiyle içerik üreticilerinin ve fotoğraf tutkunlarının tercihi.', '<p>Sony Xperia 1 VI, 6.5 inç 4K OLED ekranı ve Zeiss T* lensli üçlü kamera sistemiyle görsel kalitede rakipsiz bir deneyim sunar. Snapdragon 8 Gen 3 işlemcisi ve 5000 mAh büyük piliyle tam gün kesintisiz kullanım sağlar.</p><ul><li>6.5 inç 4K OLED, 120Hz ekran</li><li>Zeiss T* optikli 52 MP ana kamera</li><li>5000 mAh pil, 30W şarj</li><li>Snapdragon 8 Gen 3, 12 GB RAM</li><li>IP68 su ve toz geçirmezlik</li></ul>', 47999.00, 44999.00, 54, 'SNY-PHN-XP1VI', 'Sony', 7, 0.00, 0, TRUE, TRUE, '["sony","xperia","akıllı telefon","zeiss","android"]', 'Sony Xperia 1 VI', '4K OLED Ekranlı Zeiss Kameralı Telefon', NOW()),

(86, 'Motorola Edge 50 Pro 512GB Siyah', 'motorola-edge-50-pro-512gb-siyah', 'Motorola Edge 50 Pro, 165Hz pOLED ekranı ve 125W TurboPower şarjıyla hız ve konfor arayanlar için ideal mid-range amiral gemisi.', '<p>Motorola Edge 50 Pro, 6.7 inç pOLED curved ekranı ve 125W TurboPower şarj teknolojisiyle pili sadece 27 dakikada dolduran iddialı bir orta-üst segment akıllı telefondur. IP68 su geçirmezliği ve vegan deri arka yüzeyi premium tasarımı tamamlar.</p><ul><li>6.7 inç pOLED 165Hz Curved ekran</li><li>50 MP OIS ana kamera + 10 MP telefoto</li><li>125W TurboPower kablolu şarj</li><li>Snapdragon 7s Gen 2, 12 GB RAM</li><li>Vegan deri arka yüzey, IP68</li></ul>', 21999.00, 19999.00, 88, 'MOT-PHN-E50PRO', 'Motorola', 7, 0.00, 0, TRUE, FALSE, '["motorola","edge","akıllı telefon","oled","hızlı şarj"]', 'Motorola Edge 50 Pro', '165Hz OLED ve 125W Hızlı Şarj', NOW()),

(87, 'OPPO Find X7 Pro 512GB Seramik Beyaz', 'oppo-find-x7-pro-512gb-beyaz', 'OPPO Find X7 Pro, Hasselblad işbirliğiyle geliştirilen periskop kamera sistemi ve seramik arka yüzeyiyle premium segment için üretildi.', '<p>OPPO Find X7 Pro, 6.82 inç LTPO AMOLED ekranı ve Hasselblad onaylı dört kamera sistemiyle profesyonel fotoğrafçılık standartlarına yaklaşır. 100W SUPERVOOC şarj ve 50W kablosuz şarj desteğiyle enerji sorunu yaşatmaz.</p><ul><li>6.82 inç LTPO AMOLED, 120Hz</li><li>50 MP Hasselblad ana + 50 MP periskop telefoto</li><li>100W SUPERVOOC + 50W kablosuz şarj</li><li>Snapdragon 8 Gen 3, 16 GB RAM</li><li>Seramik arka panel, IP68</li></ul>', 39999.00, NULL, 37, 'OPP-PHN-FX7PRO', 'OPPO', 7, 0.00, 0, TRUE, FALSE, '["oppo","find x7","akıllı telefon","hasselblad","seramik"]', 'OPPO Find X7 Pro', 'Hasselblad Kameralı Seramik Premium', NOW()),

-- ELEKTRONİK - LAPTOP (8) — 2 ürün
(88, 'Microsoft Surface Laptop 5 Intel i7 512GB Platin', 'microsoft-surface-laptop-5-i7-512gb-platin', 'Surface Laptop 5, dokunmatik PixelSense ekranı ve ince alüminyum kasasıyla kurumsal ve yaratıcı kullanıcılara şık bir iş istasyonu sunar.', '<p>Microsoft Surface Laptop 5, 13.5 inç PixelSense dokunmatik ekranı ve Alcantara klavye yüzeyi ile hem estetik hem ergonomik bir deneyim sunar. Intel Core i7-1265U ve 16 GB RAM ile ofis ve içerik üretim görevlerini kolayca kaldırır.</p><ul><li>13.5 inç PixelSense 2256x1504 dokunmatik ekran</li><li>Intel Core i7-1265U, 16 GB LPDDR5X RAM</li><li>512 GB SSD, Thunderbolt 4</li><li>18 saate kadar pil ömrü</li><li>Alcantara klavye yüzeyi, Windows 11</li></ul>', 64999.00, 59999.00, 27, 'MSF-LAP-SL5I7PT', 'Microsoft', 8, 0.00, 0, TRUE, TRUE, '["microsoft","surface","laptop","windows","dokunmatik"]', 'Microsoft Surface Laptop 5', 'Şık Tasarım ve Dokunmatik Ekran', NOW()),

(89, 'HP Spectre x360 14 Intel i7 OLED 2-in-1', 'hp-spectre-x360-14-i7-oled-2in1', 'HP Spectre x360 14, 360 derece dönen OLED ekranı ve Intel Evo sertifikasıyla laptop ve tablet deneyimini tek cihazda birleştiriyor.', '<p>HP Spectre x360 14, 2.8K OLED dokunmatik ekranı 360 derece katlanabilir tasarımla laptop, tablet, stand ve çadır modlarında kullanılmasını sağlar. Intel Evo sertifikası anlık uyandırma ve üstün pil ömrünü garanti eder.</p><ul><li>14 inç 2.8K OLED dokunmatik, 120Hz</li><li>Intel Core i7-1355U, 16 GB RAM</li><li>1 TB SSD, Thunderbolt 4</li><li>17 saate kadar pil ömrü</li><li>HP Sure View gizlilik ekranı, Intel Evo</li></ul>', 71999.00, NULL, 19, 'HPQ-LAP-SX36014', 'HP', 8, 0.00, 0, TRUE, FALSE, '["hp","spectre","2-in-1","oled","laptop"]', 'HP Spectre x360 14 OLED', 'Dönüştürülebilir OLED 2-in-1 Laptop', NOW()),

-- ELEKTRONİK - TABLET (9) — 2 ürün
(90, 'Microsoft Surface Pro 10 Intel Core Ultra 7 Wi-Fi', 'microsoft-surface-pro-10-core-ultra7-wifi', 'Surface Pro 10, ince ve hafif gövdesinde Intel Core Ultra 7 çipi ve yapay zeka destekli Windows 11 ile iş gücü platformu.', '<p>Microsoft Surface Pro 10, ince tasarımına rağmen Intel Core Ultra 7 165H işlemcisi ve NPU donanımlı yapay zeka desteğiyle ofis verimliliğini zirveye taşır. Detachable klavye ve Surface Slim Pen 2 ile tam masaüstü deneyimi sağlar.</p><ul><li>13 inç PixelSense Flow 120Hz ekran</li><li>Intel Core Ultra 7 165H, 16 GB RAM</li><li>512 GB SSD, Thunderbolt 4</li><li>Yapay Zeka destekli NPU işlemci</li><li>USB-A, USB-C, Surface Connect port</li></ul>', 52999.00, NULL, 31, 'MSF-TAB-SP10CU7', 'Microsoft', 9, 0.00, 0, TRUE, FALSE, '["microsoft","surface pro","tablet","windows","yapay zeka"]', 'Microsoft Surface Pro 10', 'Yapay Zeka Destekli 2-in-1 Tablet', NOW()),

(91, 'Xiaomi Pad 6S Pro 12.4" 512GB Wi-Fi', 'xiaomi-pad-6s-pro-12-4-512gb-wifi', 'Xiaomi Pad 6S Pro, 3K ekranı ve Snapdragon 8 Gen 2 çipiyle yüksek çözünürlüklü içerik tüketimi ve çizim için güçlü bir Android tablettir.', '<p>Xiaomi Pad 6S Pro, 12.4 inç 3K LCD ekranı ve Snapdragon 8 Gen 2 işlemcisiyle grafik yoğun uygulamalarda akıcı bir deneyim sunar. 144Hz yenileme hızı ve Xiaomi Smart Pen 2 ile hem yaratıcı çalışmalar hem de not alma kolaylaşır.</p><ul><li>12.4 inç 3K LCD, 144Hz</li><li>Snapdragon 8 Gen 2, 12 GB RAM</li><li>512 GB depolama, microSD desteği</li><li>10000 mAh pil, 120W şarj</li><li>Dört hoparlör, Dolby Atmos, HiRes Audio</li></ul>', 24999.00, 22499.00, 59, 'XMI-TAB-P6SPR12', 'Xiaomi', 9, 0.00, 0, TRUE, FALSE, '["xiaomi","pad","tablet","3k","android"]', 'Xiaomi Pad 6S Pro', '3K 144Hz Ekranlı Güçlü Android Tablet', NOW()),

-- ELEKTRONİK - KULAKLIK (10) — 2 ürün
(92, 'Sennheiser Momentum 4 Wireless Siyah', 'sennheiser-momentum-4-wireless-siyah', 'Sennheiser Momentum 4, 60 saatlik pil ömrü ve Adaptive ANC teknolojisiyle uzun seyahatler için müzisyenler kalibresinde ses sunar.', '<p>Sennheiser Momentum 4, 42mm özel geliştirme transducer ile kulak üstü kulaklıkta müzik yayıncısı doğruluğunu sağlar. 60 saate kadar pil ömrü ve Adaptive ANC sistemi ile uçuş ve toplu taşıma ortamlarında sessiz bir dinleme deneyimi yaşatır.</p><ul><li>60 saate kadar pil ömrü (ANC dahil)</li><li>Sennheiser Adaptive ANC</li><li>42mm özel transducer</li><li>Çoklu cihaz bağlantısı (Multipoint)</li><li>Katlanabilir tasarım, deri yastık</li></ul>', 11499.00, 9999.00, 73, 'SEN-AUD-MM4WLK', 'Sennheiser', 10, 0.00, 0, TRUE, TRUE, '["sennheiser","kulaklık","anc","kablosuz","hi-fi"]', 'Sennheiser Momentum 4', '60 Saat Pilli Premium Kulaklık', NOW()),

(93, 'Samsung Galaxy Buds3 Pro Gümüş TWS Kulaklık', 'samsung-galaxy-buds3-pro-gumus-tws', 'Galaxy Buds3 Pro, Intelligent ANC ve 360 Ses teknolojisiyle Samsung ekosistemiyle tam entegre çalışan kulak içi kulaklık.', '<p>Samsung Galaxy Buds3 Pro, ANC ve Hi-Fi ses kalitesini kolayca taşınabilir kulak içi formatta sunar. Blade design ve LED şerit tasarımı göze çarpan bir estetik yaratırken 360 Ses ve SSC HiFi codec üstün ses deneyimi sağlar.</p><ul><li>Intelligent ANC ve ortam sesi</li><li>360 Ses (Spatial Audio)</li><li>SSC HiFi codec desteği</li><li>6 saat pil + kılıfla 26 saat</li><li>IP57 toz ve su direnci</li></ul>', 8999.00, NULL, 106, 'SAM-AUD-GB3PRGM', 'Samsung', 10, 0.00, 0, TRUE, FALSE, '["samsung","galaxy buds","tws","anc","spatial audio"]', 'Samsung Galaxy Buds3 Pro', 'Hi-Fi ve ANC Özellikli TWS Kulaklık', NOW()),

-- GİYİM - TİŞÖRT (11) — 2 ürün
(94, 'Patagonia Capilene Cool Daily Erkek Tişört Lacivert', 'patagonia-capilene-cool-daily-erkek-tisort', 'Patagonia Capilene Cool Daily, geri dönüştürülmüş polyester ve doğal koku kontrolüyle outdoor ve günlük kullanımda ideal teknik tişört.', '<p>Patagonia Capilene Cool Daily, %100 geri dönüştürülmüş polyester ve Polygiene® koku önleyici teknolojisiyle hem çevre dostu hem de performans odaklı bir tişörttür. Güneş koruması ve hafif yapısıyla trekking, seyahat ve günlük kullanıma eşit uyum sağlar.</p><ul><li>%100 geri dönüştürülmüş polyester</li><li>Polygiene® kalıcı koku önleme</li><li>UPF 25+ güneş koruması</li><li>Hafif, hızlı kuruyan kumaş</li><li>Fair Trade Sertifikalı üretim</li></ul>', 1499.00, NULL, 192, 'PAT-TSH-CPCDLYLN', 'Patagonia', 11, 0.00, 0, TRUE, FALSE, '["patagonia","tişört","outdoor","sürdürülebilir","dri-fit"]', 'Patagonia Capilene Cool Daily', 'Sürdürülebilir Teknik Outdoor Tişört', NOW()),

(95, 'Lacoste Classic Pique Polo Tişört Beyaz L.12.12', 'lacoste-classic-pique-polo-l1212-beyaz', 'Lacoste L.12.12, 1933''ten bu yana üretilen ikonik timsah logolu klasik pike polo tişört.', '<p>Lacoste L.12.12, özel baskı desenli pike kumaşı ve ikonik yeşil timsah logosunun göğüse nakışıyla sade şıklığın simgesidir. Slim fit kesim ve örgü polo yaka, iş casual kombinlerden hafta sonu buluşmalarına kadar her ortama uygundur.</p><ul><li>%100 Pique pamuk, sıkı dokuma</li><li>Slim fit, klasik polo yaka</li><li>Ikonik timsah nakış detayı</li><li>Yandan yırtmaçlı alt etek</li><li>Makine yıkama uyumlu, renk haslığı yüksek</li></ul>', 2199.00, 1799.00, 145, 'LAC-TSH-CL1212WH', 'Lacoste', 11, 0.00, 0, TRUE, FALSE, '["lacoste","polo","tişört","klasik","pamuk"]', 'Lacoste Classic Polo L.12.12', 'Ikonik Timsah Logolu Polo Tişört', NOW()),

-- GİYİM - SWEATSHİRT (12) — 2 ürün
(96, 'New Balance Athletics Fleece Kapüşonlu Sweatshirt Siyah', 'new-balance-athletics-fleece-hoodie-siyah', 'New Balance Athletics Fleece Hoodie, ağır gramaj pamuklu fleece ve büyük ön logo baskısıyla spor heritage stilini yansıtır.', '<p>New Balance Athletics koleksiyonundan bu hoodie, ağır gramaj French terry fleece kumaşı ve bold NB logo baskısıyla hem sokak stiline hem de spor ortamına hitap eder. Kangaroo cep ve ayarlanabilir kapüşon pratik kullanım sağlar.</p><ul><li>%80 pamuk, %20 polyester ağır gramaj fleece</li><li>Bold NB Athletics logo baskı</li><li>Kangaroo ön cep</li><li>Elastik bileklik ve bel bandı</li><li>Oversize fit, unisex tasarım</li></ul>', 2399.00, NULL, 117, 'NBL-SWT-ATFLHDK', 'New Balance', 12, 0.00, 0, TRUE, FALSE, '["new balance","hoodie","sweatshirt","fleece","athletics"]', 'New Balance Athletics Hoodie', 'Spor Heritage Stilinde Ağır Gramaj Hoodie', NOW()),

(97, 'Carhartt WIP Chase Crew Neck Sweatshirt Haki', 'carhartt-wip-chase-crew-sweatshirt-haki', 'Carhartt WIP Chase Sweatshirt, sağlam pamuklu fransız havlu dokusu ve iş etiketli logo nakışıyla workwear estetiğini streetwear''a taşıyor.', '<p>Carhartt WIP Chase, %100 pamuk Molleton kumaşından üretilmiş crew neck sweatshirt; iş kıyafeti dayanıklılığını şehir stiline uyarlar. Küçük C logosu nakışı ve beyaz şerit detayıyla minimalist ama ayırt edici bir görünüm sunar.</p><ul><li>%100 ağır gramaj pamuk Molleton</li><li>Küçük C Logo nakış + şerit detay</li><li>Crew neck, bant yaka</li><li>Ribana bileklik ve bel</li><li>Regular fit, unisex</li></ul>', 2699.00, NULL, 94, 'CRH-SWT-CHSCRHK', 'Carhartt', 12, 0.00, 0, TRUE, FALSE, '["carhartt","sweatshirt","crew neck","workwear","streetwear"]', 'Carhartt WIP Chase Crew', 'Workwear Dayanıklılığı Sokak Stilinde', NOW()),

-- GİYİM - PANTOLON (13) — 2 ürün
(98, 'Patagonia Quandary Pants Erkek Outdoor Pantolon Gri', 'patagonia-quandary-pants-erkek-gri', 'Patagonia Quandary Pants, hafif ve streçli DWR kaplı nylon dokusuyla climbing, trekking ve günlük kullanımda çok yönlü outdoor pantolonudur.', '<p>Patagonia Quandary Pants, Fair Trade sertifikalı üretimi ve DWR kaplı hafif nylon kumasıyla trekking, kayalık arazi ve şehir kullanımına eşit uyum sağlar. Esnek bel bandı ve diz altı artikülasyonu tam hareket özgürlüğü sağlar.</p><ul><li>%95 nylon, %5 elastan, DWR kaplama</li><li>Gizli kemer döngüsü, iç bel ayarı</li><li>4 yönlü streç, diz artikülasyonu</li><li>Fermuarlı kalça ve arka cep</li><li>Fair Trade Sertifikalı üretim</li></ul>', 3199.00, NULL, 74, 'PAT-PNT-QNDRYPGR', 'Patagonia', 13, 0.00, 0, TRUE, FALSE, '["patagonia","outdoor","pantolon","trekking","streç"]', 'Patagonia Quandary Pants', 'Çok Yönlü DWR Kaplı Outdoor Pantolonu', NOW()),

(99, 'G-Star RAW 3301 Slim Fit Erkek Denim Pantolon Koyu Mavi', 'g-star-raw-3301-slim-fit-erkek-denim', 'G-Star RAW 3301, raw denim kültürünü slim fit kesim ve 3D biçimlendirilmiş dikiş teknolojisiyle modern günlük stile taşıyor.', '<p>G-Star RAW 3301, 3D biçimlendirilmiş dikiş tekniği sayesinde vücut siluetine mükemmel uyum sağlayan slim fit bir denim pantolondur. Yıkanmamış (raw) 12 oz selvedge denim zamanla kullanıcının vücuduna göre şekil alarak kişiselleşir.</p><ul><li>12 oz ham selvedge denim</li><li>3D contour dikişi, slim fit</li><li>Siyah bant detayı arka cep</li><li>Orta bel yüksekliği, tapered bacak</li><li>Koyu mavi (Dark Aged wash)</li></ul>', 2999.00, 2499.00, 108, 'GST-PNT-3301SLDB', 'G-Star RAW', 13, 0.00, 0, TRUE, FALSE, '["g-star","denim","pantolon","slim","raw"]', 'G-Star RAW 3301 Slim', '3D Dikiş Teknolojili Premium Denim', NOW()),

-- AYAKKABI - SPOR AYAKKABI (15) — 2 ürün
(100, 'Hoka Clifton 9 Erkek Koşu Ayakkabısı Gece Mavisi', 'hoka-clifton-9-erkek-gece-mavisi', 'Hoka Clifton 9, tam uzunlukta EVA köpük ara taban ve meta-rocker geometrisiyle maraton mesafelerinde koşucuların en yüksek konfor seçimi.', '<p>Hoka Clifton 9, belirgin düz taban tasarımı ve tam uzunluk EVA köpüğüyle uzun mesafe koşularında yorulmadan ilerlemenizi sağlar. Meta-Rocker geometrisi, topuktan parmak ucuna doğal bir yuvarlanma hareketi yaratarak enerji kaybını azaltır.</p><ul><li>Tam uzunlukta hafif EVA ara taban</li><li>Meta-Rocker geometrisi</li><li>Engineered mesh üst, nefes alabilir</li><li>Ezilmeye dayanıklı topuk kumaşı</li><li>Erkek: 40-47 beden aralığı</li></ul>', 6499.00, NULL, 87, 'HOK-SNK-CLF9NVY', 'Hoka', 15, 0.00, 0, TRUE, FALSE, '["hoka","clifton","koşu","maximal","spor ayakkabı"]', 'Hoka Clifton 9', 'Maksimal Yastıklama ile Uzun Mesafe Konforu', NOW()),

(101, 'Brooks Ghost 16 Erkek Koşu Ayakkabısı Beyaz/Mavi', 'brooks-ghost-16-erkek-beyaz-mavi', 'Brooks Ghost 16, DNA LOFT v3 köpük ara taban ve 3D Fit Print teknolojisiyle nötr koşucular için birinci sınıf koşu deneyimi sunar.', '<p>Brooks Ghost 16, güncellenmiş DNA LOFT v3 köpük formülüyle daha yumuşak ve daha tepkili bir koşu deneyimi sunacak şekilde yeniden tasarlandı. 3D Fit Print teknolojisi, dikişsiz bir üst yapı ile ayak şekillerine kusursuz uyum sağlar.</p><ul><li>DNA LOFT v3 köpük ara taban</li><li>3D Fit Print dikişsiz üst</li><li>Omega Flex Grooves esnek taban</li><li>Segmentli çarpışma bölgesi</li><li>Erkek/Kadın geniş beden aralığı</li></ul>', 5999.00, NULL, 61, 'BRK-SNK-GH16WBL', 'Brooks', 15, 0.00, 0, TRUE, FALSE, '["brooks","ghost","koşu","dna loft","spor ayakkabı"]', 'Brooks Ghost 16', 'Nötr Koşucular İçin Premium Koşu Ayakkabısı', NOW()),

-- AYAKKABI - SNEAKER (16) — 2 ürün
(102, 'Nike Dunk Low Retro Panda Siyah/Beyaz', 'nike-dunk-low-retro-panda-siyah-beyaz', 'Nike Dunk Low Retro Panda, ikonik siyah-beyaz renk blok tasarımıyla tüm zamanların en çok aranan sneaker silüetlerinden biri olmaya devam ediyor.', '<p>Nike Dunk Low, 1985''te basketbol sahalarında doğan ve bugün sneaker kültürünün tartışmasız simgelerinden biri haline gelen tasarımını aynen korur. Panda olarak bilinen siyah-beyaz colorway temiz ve çok yönlü görünümüyle her kombin ile uyum sağlar.</p><ul><li>Deri ve sentetik deri üst kısım</li><li>Daha ince dil ve bileklik, düşük profil</li><li>Nike Air yastıklaması (heel)</li><li>Kauçuk dış taban</li><li>Ikonik Swoosh ve top-cap detayı</li></ul>', 3999.00, NULL, 213, 'NKE-SNK-DKLWPND', 'Nike', 16, 0.00, 0, TRUE, TRUE, '["nike","dunk low","panda","sneaker","retro"]', 'Nike Dunk Low Retro Panda', 'Tüm Zamanların En İkonik Sneaker Colorway''i', NOW()),

(103, 'Reebok Classic Leather Gri/Gum Erkek Sneaker', 'reebok-classic-leather-gri-gum-erkek', 'Reebok Classic Leather, 1983''ten beri değişmeyen deri üst ve lastik taban kombinasyonuyla retro sneaker segmentinin vazgeçilmezi.', '<p>Reebok Classic Leather, orijinal 1983 koşu ayakkabısı tasarımından ilham alan düz profili ve tam tahıl deri üst kısımıyla vintage sneaker estetiğini günümüze taşır. Gum taban detayı otantik 80ler stilini tamamlar.</p><ul><li>Tam tahıl deri üst kısım</li><li>EV yastıklama ara taban</li><li>Gum lastik dış taban</li><li>Klasik düşük profil tasarım</li><li>Unisex, geniş beden aralığı</li></ul>', 2699.00, 2199.00, 155, 'RBK-SNK-CLLTGRGM', 'Reebok', 16, 0.00, 0, TRUE, FALSE, '["reebok","classic leather","retro","sneaker","gum"]', 'Reebok Classic Leather Gri/Gum', '80ler Retro Estetiğinin Deri Klasiği', NOW()),

-- EV & YAŞAM (4) — 3 ürün
(104, 'iRobot Roomba j9+ Akıllı Robot Süpürge', 'irobot-roomba-j9-plus-akilli-robot-supurge', 'iRobot Roomba j9+, kendi kendini boşaltan şarj tabanı ve PrecisionVision navigasyonuyla tam otomatik ev temizliği sağlar.', '<p>iRobot Roomba j9+, PrecisionVision™ navigasyon sistemi sayesinde mobilya ve kablo gibi engelleri gerçek zamanlı olarak tanıyarak kaçınır. Clean Base® Otomatik Kir Boşaltma birimi, pis su dolu torbayı 60 güne kadar taşımanızı sağlar.</p><ul><li>PrecisionVision™ engellerden kaçınma</li><li>Clean Base® 60 güne kadar otomatik boşaltma</li><li>3 aşamalı temizlik sistemi</li><li>Uygulama ve sesli asistan kontrolü</li><li>Wi-Fi bağlantısı, zamanlama</li></ul>', 22999.00, 19999.00, 21, 'IRB-HOM-RBJ9PLUS', 'iRobot', 4, 0.00, 0, TRUE, TRUE, '["irobot","roomba","robot süpürge","akıllı ev","otomasyon"]', 'iRobot Roomba j9+', 'Kendi Kendini Boşaltan Robot Süpürge', NOW()),

(105, 'Smeg FAB28 Retro Buzdolabı Krem', 'smeg-fab28-retro-buzdolabi-krem', 'Smeg FAB28, 50ler İtalyan tasarım estetiğini A++ enerji sınıfıyla birleştiren dekoratif ve fonksiyonel tek kapılı buzdolabı.', '<p>Smeg FAB28, ikonik yuvarlak hatları ve pastel renk seçenekleriyle mutfağınıza estetik bir odak noktası olur. Dahili fanı sayesinde eşit soğutma sağlar, üstteki derin dondurucu bölme ile günlük saklama ihtiyaçlarınızı karşılar.</p><ul><li>270 litre net hacim (222L soğutucu + 26L dondurucu)</li><li>A++ enerji sınıfı</li><li>Dahili fan, eşit soğutma</li><li>Ayarlanabilir cam raflar</li><li>2 yıl resmi Smeg garantisi</li></ul>', 34999.00, NULL, 14, 'SMG-HOM-FAB28CR', 'Smeg', 4, 0.00, 0, TRUE, FALSE, '["smeg","buzdolabı","retro","tasarım","mutfak"]', 'Smeg FAB28 Retro Buzdolabı', '50ler İtalyan Tasarımı ile A++ Soğutma', NOW()),

(106, 'Weber Spirit E-315 3 Gözlü Gazlı Izgarası', 'weber-spirit-e-315-3-goz-gazli-izgara', 'Weber Spirit E-315, üç adet bağımsız kontrol edilebilir yanıcısı ve GS4 ızgara sistemiyle her mevsim mükemmel barbeküyü garantiler.', '<p>Weber Spirit E-315, paslanmaz çelik GS4 yanıcıları ve porselen emaye kapağıyla uzun ömürlü ve verimli bir ızgara deneyimi sunar. Yan tezgah, baharatlar ve araçlar için ek alan sağlarken Snap-Jet ateşleme sistemi güvenli tutuşma sağlar.</p><ul><li>3 adet GS4 yüksek performanslı yanıcı</li><li>Toplam 10500 kcal/h ısı çıkışı</li><li>Porselen emaye kapak ve ızgara ızgarası</li><li>Snap-Jet bağımsız ateşleme sistemi</li><li>10 yıl yanıcı garantisi</li></ul>', 17999.00, 15999.00, 18, 'WBR-HOM-SPE315', 'Weber', 4, 0.00, 0, TRUE, FALSE, '["weber","izgara","barbeku","gazlı","outdoor"]', 'Weber Spirit E-315 Gazlı Izgara', 'Üç Yanıcılı Profesyonel Ev Izgarası', NOW()),

-- SPOR & OUTDOOR (5) — 3 ürün
(107, 'Garmin Fenix 7X Solar GPS Outdoor Saat Titanium', 'garmin-fenix-7x-solar-gps-outdoor-saat', 'Garmin Fenix 7X Solar, güneş enerjisiyle şarj özelliği ve multi-sport GPS takibiyle zorlu outdoor koşulları için tasarlanmış premium akıllı saat.', '<p>Garmin Fenix 7X Solar, Power Glass™ güneş şarj lensleri sayesinde GPS modunda 37 güne kadar pil ömrü sunar. Titanyum kasa ve safir ekranıyla yüksek dayanıklılık gerektiren tırmanış, triatlon ve ski gibi disiplinlerde güvenilir bir eşlik eder.</p><ul><li>Power Glass™ güneş şarj lensi</li><li>37 güne kadar GPS pil ömrü</li><li>Titanyum kasa + Safir ekran</li><li>Multi-band GPS, çoklu spor profili</li><li>100 metre su direnci, dalış desteği</li></ul>', 23999.00, NULL, 26, 'GRM-SPT-FNX7XSL', 'Garmin', 5, 0.00, 0, TRUE, TRUE, '["garmin","fenix","gps saat","outdoor","solar"]', 'Garmin Fenix 7X Solar', 'Güneş Enerjili Titanium Outdoor GPS Saati', NOW()),

(108, 'Black Diamond Crag Daddy 35L Tırmanış Çantası', 'black-diamond-crag-daddy-35l-tirmanis-cantasi', 'Black Diamond Crag Daddy 35L, haul kapı ve ip bölmesiyle kaya tırmanışı için özel tasarlanmış teknik sırt çantasıdır.', '<p>Black Diamond Crag Daddy 35L, tırmanış ekipmanınızı taşımayı kolaylaştıran özel haul kapısı ve ayrı ip bölmesiyle kaya tırmanışı için optimize edilmiş bir sırt çantasıdır. Bölümlere ayrılmış ana hacmi ve dış bağlantı noktaları ile ekipman organizasyonunu basitleştirir.</p><ul><li>35 litrelik hacim, tırmanış organize bölmeler</li><li>Haul kapısı (alt açılım)</li><li>Ayrı ip bölmesi</li><li>Karabina askı döngüleri</li><li>Hydration uyumlu, sternum straps</li></ul>', 4299.00, NULL, 43, 'BLD-SPT-CD35TRN', 'Black Diamond', 5, 0.00, 0, TRUE, FALSE, '["black diamond","tırmanış","sırt çantası","outdoor","crag"]', 'Black Diamond Crag Daddy 35L', 'Kaya Tırmanışı İçin Teknik Sırt Çantası', NOW()),

(109, 'Suunto Race Titanium GPS Koşu ve Triatlon Saati', 'suunto-race-titanium-gps-kos-saat', 'Suunto Race Titanium, AMOLED ekran ve 85 saatlik GPS pil ömrüyle ultra maratonlarda ve triatlonlarda güvenilir yol arkadaşı.', '<p>Suunto Race Titanium, canlı AMOLED dokunmatik ekranı ve 85 saate kadar GPS pil ömrüyle ultra mesafe koşucuları ve iron-man triatletlerine yönelik tasarlanmıştır. Otomatik segment algılama ve gerçek zamanlı koşu güç metrikleri antrenman kalitesini artırır.</p><ul><li>AMOLED dokunmatik ekran</li><li>85 saate kadar GPS pil ömrü</li><li>Titanyum kasa, 100m su geçirmezlik</li><li>Otomatik segment ve tempo takibi</li><li>Suunto App ile antrenman analizi</li></ul>', 16999.00, NULL, 31, 'SUT-SPT-RACETITGP', 'Suunto', 5, 0.00, 0, TRUE, FALSE, '["suunto","gps saat","triatlon","koşu","titanium"]', 'Suunto Race Titanium', '85 Saat GPS Pilli Triatlon ve Ultra Koşu Saati', NOW());

-- 2. Insert Images
INSERT INTO product_images
  (product_id, image_url, alt_text, is_primary, sort_order)
VALUES
(85, 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&h=600&fit=crop', 'Sony Xperia 1 VI', TRUE, 1),
(86, 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&h=600&fit=crop', 'Motorola Edge 50 Pro', TRUE, 1),
(87, 'https://images.unsplash.com/photo-1580910051074-3eb694886505?w=800&h=600&fit=crop', 'OPPO Find X7 Pro', TRUE, 1),
(88, 'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=800&h=600&fit=crop', 'Microsoft Surface Laptop 5', TRUE, 1),
(89, 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=800&h=600&fit=crop', 'HP Spectre x360 14 OLED', TRUE, 1),
(90, 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800&h=600&fit=crop', 'Microsoft Surface Pro 10', TRUE, 1),
(91, 'https://images.unsplash.com/photo-1561154464-82e9adf32764?w=800&h=600&fit=crop', 'Xiaomi Pad 6S Pro', TRUE, 1),
(92, 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&h=600&fit=crop', 'Sennheiser Momentum 4', TRUE, 1),
(93, 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&h=600&fit=crop', 'Samsung Galaxy Buds3 Pro', TRUE, 1),
(94, 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&h=600&fit=crop', 'Patagonia Capilene Tişört', TRUE, 1),
(95, 'https://images.unsplash.com/photo-1625910513823-2e4dd8c41c6b?w=800&h=600&fit=crop', 'Lacoste Classic Polo', TRUE, 1),
(96, 'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800&h=600&fit=crop', 'New Balance Athletics Hoodie', TRUE, 1),
(97, 'https://images.unsplash.com/photo-1614975059251-992f11792b9f?w=800&h=600&fit=crop', 'Carhartt WIP Chase Crew', TRUE, 1),
(98, 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&h=600&fit=crop', 'Patagonia Quandary Pants', TRUE, 1),
(99, 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&h=600&fit=crop', 'G-Star RAW 3301 Slim', TRUE, 1),
(100, 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=600&fit=crop', 'Hoka Clifton 9', TRUE, 1),
(101, 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&h=600&fit=crop', 'Brooks Ghost 16', TRUE, 1),
(102, 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800&h=600&fit=crop', 'Nike Dunk Low Panda', TRUE, 1),
(103, 'https://images.unsplash.com/photo-1515955656352-a1fa3ffcd111?w=800&h=600&fit=crop', 'Reebok Classic Leather', TRUE, 1),
(104, 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&h=600&fit=crop', 'iRobot Roomba j9+', TRUE, 1),
(105, 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&h=600&fit=crop', 'Smeg FAB28 Retro Buzdolabı', TRUE, 1),
(106, 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=600&fit=crop', 'Weber Spirit E-315 Izgara', TRUE, 1),
(107, 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&h=600&fit=crop', 'Garmin Fenix 7X Solar', TRUE, 1),
(108, 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&h=600&fit=crop', 'Black Diamond Crag Daddy', TRUE, 1),
(109, 'https://images.unsplash.com/photo-1510771463146-e89e6e86560e?w=800&h=600&fit=crop', 'Suunto Race Titanium', TRUE, 1);

-- 3. Link products to seller_id = 3
-- (Assumes junction table: seller_products or products.seller_id column)
-- If products table has a seller_id column, use the UPDATE below:
UPDATE products SET seller_id = 3 WHERE id BETWEEN 85 AND 109;

SET foreign_key_checks = 1;
